template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0

# Discovery-related settings.
discovery:
  serviceName: hello-world
  hosts:
  # blah, cannot be 127.0.0.1
      - localhost
